### ISSUE TITLE
docs: Document the interface required to be implemented for custom stores

### ISSUE THREAD

**Issue by dan-turner** [node-cache-manager/node-cache-manager#128]
Hello,

It would be super useful if in the Readme it described the interface that should be implemented if creating a custom store.  I would like to have a crack at building a firebase backed store, but having a brief look at some of the example stores it difficult to work out exactly what the contract is.

**Comment by BryanDonovan** [comment]
Yeah, more docs on that would be good.  I'm not sure if I'll have time to do that any time soon though.  In the meantime, all you really need to do is implement basic get/set methods like the ones referenced here: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L238

**Comment by botika** [comment]
Fixes by #203
