### ISSUE TITLE
unclear usage for multiple keys with wrap

### ISSUE THREAD

**Issue by ybayk** [node-cache-manager/node-cache-manager#130]
From read-me:

```
memoryCache.wrap(key1, key2, function (cb) {
    getManyUser([key1, key2], cb);
}, function (err, users) {
    console.log(users[0]);
    console.log(users[1]);
});

```

Not clear what happens, if key1 already in cache and key2 is NOT?
For sure I do not want to call getManyUser() with with both [key1,key2], so how do I know to pass just key2, and still get all users (cached and just fetched) in the bottom callback?

**Comment by BryanDonovan** [comment]
Hi, sorry for the delayed response.

I didn't write that bit of code, so I'm looking into it now to see how it works.  Here's the code that gets called: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L159

**Comment by BryanDonovan** [comment]
I added some more info in the README about this, and added a couple more tests in `caching.unit.js`.  In summary, the cache does not work like you probably want it to.  It returns whatever records it finds in the cache and doesn't fill in the rest from the underlying datastore.  See https://github.com/BryanDonovan/node-cache-manager/commit/a09d730840e14d607eede3bf890832d8470577e5

CC @sebelga

**Comment by ybayk** [comment]
Thank you for looking at this. From the new unit tests, do i get it right that the top callback is not actually called at all if keys are hit partially? And only the bottom callback is called with just the objects retrieved from the cache? 
Would it be feasible to make a little enhancement to actually call the top callback with an extra parameter that would represent a list of missing keys?

**Comment by BryanDonovan** [comment]
I think you're right about how it works.  Calling back with an extra parameter like `{info: {keysNotFoundInCache: [...array of keys]}}` might work.

**Comment by ybayk** [comment]
Ok, in that case a workaround for the current behavior would look like this:
```
function getUsers(keys, callback) {
  cache.wrap(...keys, cacheCallback => {
    //current cache-manager behavior is to call first callback when all keys are missed
    doRequest(keys, cacheCallback);
  }, (err, users) => {
    //current cache-manager behavior: this callback is going to be called only for cached hits
    if (err) {
      callback(err, null);
    } else {
      //build key-to-user map required to merge final results
      let userMap = new Map();

      users.forEach(user=>{
        userMap.set(user.key, user);
      });
      //determine for which keys we got cache results
      let missedKeys = keys.filter(key=>!userMap.has(key));

      doRequest(missedKeys, (err2, users2)=>{
        if (err2) {
          callback(err2, null);
          return;
        }

        //prepare array of key, value pairs for mset
        let keyValuesToCache = [];

        missedKeys.forEach((key,idx)=>{
          keyValuesToCache.push(key);
          keyValuesToCache.push(users2[idx])
          userMap.set(key, users2[idx]);
        });

        //populate cache manually
        cache.mset(...keyValuesToCache, {});

        //finally return users in order of input keys
        callback(null, appIds.map(key=>resultMap.get(key)));
      });
    }
  });
}

```

Pretty ugly indeed, and I am afraid unreasonable to use.

**Comment by BryanDonovan** [comment]
Yes, I've had to implement something similar myself at work.  Not pretty at all.  If someone can build this into `node-cache-manager`, I'm happy to accept a pull request.  I don't have time to do it myself though.

**Comment by sebelga** [comment]
Hi,
Yes, the behavior of going to the DB to fetch the entities was indeed not added. I do think though that you don't need to add all this logic for each resource but you could extract it to make it generic.
I don't have time either right now to look into it, unfortunately.

**Comment by MarkusJ13** [comment]
The instructions are not at all clear, had to spend much time to find correct usage myself. Few cases where I got into issues are-

memoryCache.wrap(...array, function (cb) {
...

If length of array is zero, it will fail.
If length of array is one, it will return object (where as array with one element was expected).

So I had to consider these two cases myself.

**Comment by sebelga** [comment]
If you want to open a PR for it that would be great 😊

**Comment by botika** [comment]
Removed by #203. Remove multiple keys with wrap. Use various calls and `Promise.all`
