### ISSUE TITLE
callback on memory store key expiration

### ISSUE THREAD

**Issue by amit777** [node-cache-manager/node-cache-manager#153]
Is there a way to run a callback function with the value of the key that is expiring from the memory store?  like an onExpired or something similar.

**Comment by BryanDonovan** [comment]
The `dispose` option might work (see https://github.com/isaacs/node-lru-cache#options).  Whatever you pass in to the memory store gets passed to the LruCache: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L37

**Comment by botika** [comment]
I don't think this can be implemented with all stores. For example, how would you do it with Redis? I don't think it's feasible. 

@amit777 Can you give me an example of how to implement OnExpire in a Redis based store? If not I will have to close it.

**Comment by amit777** [comment]
Hi, thanks for looking into this. It's not very needed for me. But just as an FYI, Redis does seem to support key space notifications: https://medium.com/nerd-for-tech/redis-getting-notified-when-a-key-is-expired-or-changed-ca3e1f1c7f0a

**Comment by botika** [comment]
But need to turn on the notifications feature in redis. 

I can put an optional method in the `Store`. In the next version I will look at it in more detail.

**Comment by bivas6** [comment]
> The `dispose` option might work (see https://github.com/isaacs/node-lru-cache#options). Whatever you pass in to the memory store gets passed to the LruCache: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L37

Hi @BryanDonovan , 
How do you suggest to pass this option?  The second link you add gives 404...
I tried:
```
aching({
  store: 'memory',
  max: 1000,
  ttl: 5 * 60 * 100,
  dispose: (token: Token, _key: string, _reason: string) => {
    logger.error('delete key is called');
    clearFromMem(token);
});
```
and it doesn't seems to work.

Thanks!

**Comment by jaredwray** [comment]
@bivas6 are you still having this issue?
