### ISSUE TITLE
setnx is not supported

### ISSUE THREAD

**Issue by raul-j** [node-cache-manager/node-cache-manager#184]
Hello, 

Any idea if it is possible to use the REDIS command SETNX ?
https://redis.io/commands/setnx
It looks to me like it is not available

Thanks!

**Comment by BryanDonovan** [comment]
Hmm.  I'm hesitant to add Redis-specific methods to this library (and somewhat regret adding `mset`, `mget`, etc., but at least those can be implemented manually).

**Comment by raul-j** [comment]
Is there , maybe, an alternative way of doing a setnx?
Like per example, a custom command, as  a string, where the command is sent to redis, and the responsibility is then for the one using it ¿?

**Comment by BryanDonovan** [comment]
One option might be to call `getClient()` on the cache-manager-redis instance: https://github.com/dabroek/node-cache-manager-redis-store/blob/master/index.js#L9

**Comment by raul-j** [comment]
Thanks @BryanDonovan ,
that actually did the job. The counterpart is that I had to type it to any in order to work with typescript. But it is nice to be able to use raw REDIS commands without defining a new connection.

**Comment by botika** [comment]
Use implement in `Store` or get redis client reference in `Store`
