### ISSUE TITLE
difference with isCacheableValue in redis

### ISSUE THREAD

**Issue by zongzheng123** [node-cache-manager/node-cache-manager#185]
Hello, thanks to read.
i'd like to report a trap about use isCacheableValue.
if you use redis as store and set a isCacheableValue configuration, you must also return value !== null rather than just return value !== undefine,otherwise the if no cache in redis it will return null and the cache manager will sender null as cache to user to cause the problem.

```javascript
const isCacheableValue = (value: any) => {
  if () { // your custom code
  }
  return value !== undefined && value !== null
}
```

**Comment by BryanDonovan** [comment]
Thanks!

**Comment by botika** [comment]
Refactor by #203. Now `isCacheable` is implemented in every store. Not depend from cache-manager.
