### ISSUE TITLE
How to track cache hit/miss ratio?

### ISSUE THREAD

**Issue by mt3o** [node-cache-manager/node-cache-manager#195]
Hi!

I've been asked to present number of cache hits, misses and ratio, what would be the best approach? 
I haven't seen any event to hook on to extend the logic for handling the request to the cache. 
I'd rather not wrap the cache into my own class just to add such tracking.

**Comment by BryanDonovan** [comment]
Hi, sorry for the delayed response.  There is no built-in way to track this now, but your idea of emitting events would be good.  I don't have time to implement this myself but would accept a pull request.

**Comment by mt3o** [comment]
Hi
In regards to tracking the events, i wrapped your component with a component of mine that looks more or less like this:
```    
async wrap<T>(cacheKey: string, cbk) {
        this.cacheStats.reportRequest();
        return await this._caching.wrap(cacheKey, async ()=>{
            const r = await cbk();
            this.cacheStats.reportMiss();
            return r;
        });
    }
```
And in the cache class - i track each cache request, and cache miss, subtracting one from another i can get the number of hits. 
In your case - that would be like adding two fields plus few methods for getting the data, and when resetting the cache - reset the stats. 

Another way would be to have an event emitter that would just emit events on miss and on request/hit. I'm afraid that under my current load i can't make the PR, hope you understand...

**Comment by BryanDonovan** [comment]
Yeah, that looks like a pretty good solution for now.  I'll leave this open for a while in case anyone else wants to open a PR for it.

**Comment by jaredwray** [comment]
@mt3o and @BryanDonovan - going to close this out as the plan will be to get stats from Keyv as v5 is coming out in the next couple months with stats included.
