### ISSUE TITLE
Updated node-cache-manager-ioredis

### ISSUE THREAD

**Issue by Tirke** [node-cache-manager/node-cache-manager#199]
Hi,

I went ahead and did a Typescript rewrite of https://github.com/dabroek/node-cache-manager-ioredis here https://github.com/Tirke/node-cache-manager-ioredis and it is published here https://www.npmjs.com/package/@tirke/node-cache-manager-ioredis. If you want to replace the README link to this package instead of the old one, feel free.

**Comment by botika** [comment]
Closed by #200
