### ISSUE TITLE
use cache-manager in nestjs and multiple clusters

### ISSUE THREAD

**Issue by mjrajay** [node-cache-manager/node-cache-manager#201]
each _cluster_ save data in itself and don't have any data in **_redis-cli_** and **_other clusters_**  When i use **nestJs** +**cache-manager**+ **cache-manager-redis-store** + **clustring**.
i need data sharing between all clusters.
thanks

**Comment by botika** [comment]
Sorry, but this library has nothing to do with the problem you describe. I think you should ask the owner of `cache-manager-redis-store`. Or you can search for another `cache-manager + redis` library, like the `ioredis` version or thttps://github.com/node-cache-manager/node-cache-manager-redis-yet or any other listed in the readme.
