### ISSUE TITLE
Documentation in README emptied with Commit 0ba7470

### ISSUE THREAD

**Issue by simon-scherzinger** [node-cache-manager/node-cache-manager#227]
Hi,

I just saw that with commit [0ba7470](https://github.com/node-cache-manager/node-cache-manager/commit/0ba747012f2a03e7a1c13d673a82141d61868d35) the API documentation was removed from README.md. Most likely this is intentional since you are switching to Promises with Version 5.0.0? It would be awesome if you could re-add the documentation for developers who are using a version < 5.0.0.

Thanks.

Take care,

Simon

**Comment by botika** [comment]
What do you want the documentation to keep from the outdated version? Why don't you use version 5 which is self-documenting with the types? I'm sorry, but I have to delete the deprecated code. 
You can look at the documentation of version 4 in the commit that you tell me.

**Comment by BryanDonovan** [comment]
@botika - not everyone uses TypeScript or an IDE, and likely don't want to have to read through the code to figure out how it works before downloading the library.  Some basic examples in the README would probably help get people to use node-cache-manager.  The README, as it is now, tells users very little about what the library does.

**Comment by simon-scherzinger** [comment]
I'm quite sure I'm not the only one currently using a < 5.0.0 Version, since migrating to a new API without proper documentation needs time and testing. I also agree with Bryan – not everyone is using TypeScript in their projects.

I understand that you don't want to maintain the deprecated examples in the Readme. How about adding a paragraph pointing users to the [old version of the Readme](https://github.com/node-cache-manager/node-cache-manager/blob/0ba747012f2a03e7a1c13d673a82141d61868d35/README.md)? This will mitigate the time one is spending searching for the deprecated documentation.

**Comment by botika** [comment]
https://github.com/node-cache-manager/node-cache-manager/commit/9f7c46ec6142e068ea6ffe790c2e6634fda9f557
