### ISSUE TITLE
Incomplete documentation, missing features and controversial changes in v5

### ISSUE THREAD

**Issue by nicokaiser** [node-cache-manager/node-cache-manager#235]
I just tried to upgrade one of our projects to node-cache-manager@5, but gave up in frustration. The "Refactor to promise and typescript" in History.md should rather be "we're starting from scratch":

- There is no documentation at all (automatic TypeScript docs are not enough since not every project uses TypeScript)
- README.md still mentions the Express.js example (which does not work anymore with version 5)
- README.md still mentions store engines (none of them work with version 5)
- Here are only a few incompatible changes:
    - The initialization method (`caching()`) needs to be called async (states a big problem for some projects)
    - `set` method now takes `ttl` as third parameter instead of an options object (I'm not sure if some stores will require additional options beside ttl)
    - `wrap` function does not accept options anymore (cannot set custom TTL for wrapped functions)
    - TTLs now seem to be in milliseconds (which is fine), before it was specified seconds, which can lead to big confusion, especially given there is no documentation at all...

I appreciate the idea of rewriting node-cache-manager with (only) Promise support and simplifying the code by completely removing callbacks and old stuff like this. But in my opinion, this rewrite is in a very very early state of development (no documentation apart from "Refactor to promise and typescript", no support for any other than memory store, no examples, etc.) and should not be published as "stable" version 5. People might think there is an upgrade path to v5, but in most cases (when not using MemoryStore) there isn't.

**Comment by BryanDonovan** [comment]
I no longer maintain this project, but here's my input for what it's worth:

> The "Refactor to promise and typescript" in History.md should rather be "we're starting from scratch"
- Right, this definitely was a _rewrite_ with breaking changes, not a true _refactoring_.
> The initialization method (caching()) needs to be called async (states a big problem for some projects)
- I agree that it shouldn't be async.  It seems odd to have an async "constructor".  It implies that the underlying cache stores also require async initialization, which I don't think is the case.  I could be wrong though.. maybe this is the new trend.
> set method now takes ttl as third parameter instead of an options object (I'm not sure if some stores will require additional options beside ttl)
> wrap function does not accept options anymore (cannot set custom TTL for wrapped functions)
- I'm a strong proponent of using an options parameter in functions to avoid having function signatures get out of hand with too many parameters.  It makes it much easier to add more optional parameters later.  In the functions in my projects, in all but the simplest functions, I accept only a single object as a param.  In the long run, this has always been the right choice.

**Comment by botika** [comment]
@nicokaiser https://github.com/node-cache-manager/node-cache-manager/commit/0b6d0ffa5f8fdb998dad14eceb7038db254e9031 

List the features you (or any) miss. Thanks!

**Comment by nicokaiser** [comment]
> @nicokaiser [0b6d0ff](https://github.com/node-cache-manager/node-cache-manager/commit/0b6d0ffa5f8fdb998dad14eceb7038db254e9031)

This looks much better, thanks for adding examples in README.md. (The `const ttl = 5;` should read `const ttl = 5 * 1000;` or state that it's really 5 milliseconds, right?)

> List the features you (or any) miss. Thanks!

- `ttl` parameter for `wrap`
- ioredis support (I did not check yet if `node-cache-manager-redis-yet` can handle ioredis instances, but even if so, it requires quite some refactorings in the projects)
- all other stores that existed for v4 (although one might argue that having four redis modules might be a bit too much)
- sync instantiation (even the example is missing the `await` in `const memoryCache = await caching(...)`). While the other things are just a pain to refactor, this might be a blocker for some projects, since constructions like this cannot be done anymore:

```js
const express = require('express');
const { caching } = require('cache-manager');

const app = express();
const memoryCache = caching('memory', { ttl: 60 * 1000 });
app.get('/', (req, res) => res.send(memoryCache.get('foo')));
return app;

// and somewhere else:
app.listen(3000);
```

**Comment by botika** [comment]
- Express example https://github.com/node-cache-manager/node-cache-manager/commit/d1198495386ff59009a5f457bf5c4827576055b7. 
 - `ttl` parameter for `wrap` https://github.com/node-cache-manager/node-cache-manager/commit/b06c1e5b5c105addbd24ea3d9750bc28ef702437

- And no update `Stores`: These libraries do not belong to me and many are very old. I can implement io-redis. I'll try to finish it today.

By the way I am actively looking for a job urgently, I drop it there. :smile:

**Comment by botika** [comment]
https://www.npmjs.com/package/cache-manager-ioredis-yet 
I think that's all. If there is anything else do not hesitate to reopen it
