### ISSUE TITLE
v5 regression: Cached function can be called many times while waiting for it to complete using wrap

### ISSUE THREAD

**Issue by medokin** [node-cache-manager/node-cache-manager#246]
See: https://github.com/node-cache-manager/node-cache-manager/issues/8

With the current implementation the unwanted behavior is back. Example with failing test: https://github.com/node-cache-manager/node-cache-manager/pull/247

**Comment by botika** [comment]
I close, since there is no multi thread solution. If you have any multi thread solution, do not hesitate to do the PR, but I am not going to put an MAP and return Undefined, as previously made.
