### ISSUE TITLE
v5 regression: wrap() no longer re-populates higher priority caches when a key is found in lower ones.

### ISSUE THREAD

**Issue by thgreasi** [node-cache-manager/node-cache-manager#253]
When using multi-level caches eg memory & redis, when a key is not found in the higher level cache (eg memory) but it is found in the lower one (redis), the key is no longer set in the higher levels. As a result subsequent requests for the same key will always have to reach redis and consume extra bandwidth.
In v4 wrap was re-populating the higher level caches, so subsequent requests within the ttl of the memory cache did not have to reach redis.

**Comment by botika** [comment]
I understood. I look at him tomorrow morning (CET). Thank you!

**Comment by botika** [comment]
Do I leave it alone in the `wrap` or do I also put it in the `set`?
