### ISSUE TITLE
Okay to call caching multiple times?

### ISSUE THREAD

**Issue by notflip** [node-cache-manager/node-cache-manager#263]
I'm using controllers to store my route logic, if I have 5 controllers, is it ok to use `const cache = await caching('memory', { ttl: 10 * 1000, max: 500 });` at the top of every controller? Or do I have to define it once and pass the instance to others controllers?

```
export default async (req: Request<{}, {}, {}, RequestQuery>, res: Response) => {
    const cache = await caching('memory', { ttl: 10 * 1000, max: 500 });
    const searchTerm = req.query.searchTerm.toLowerCase()
}
```

**Comment by botika** [comment]
No. If you need a software engineer I'm looking for a job.
