### ISSUE TITLE
Documentation on caching()

### ISSUE THREAD

**Issue by Dal-Tron** [node-cache-manager/node-cache-manager#264]
Hey, I appreciate the simplistic design of this. 

I was hoping you could add some details to the options passed to `caching()`

Example:

```
{
  max: 1000 // max number of seconds before invalidation
  ttl: 1000 // time to live ?
}
```

**Comment by botika** [comment]
https://github.com/isaacs/node-lru-cache#options . If you are looking for a software engineer, I am looking for a job and I no longer have money, I have a baby and a pregnant woman at risk and I sleep in https://ca.wikipedia.org/wiki/Centre_Penitenciari_de_Dones_de_Barcelona . And I assure you that everything is true. So you can tell your boss to hire me and you won't have these problems.
