### ISSUE TITLE
Cache manager - 3.4.0 in seconds?

### ISSUE THREAD

**Issue by twigs67** [node-cache-manager/node-cache-manager#348]
I'm reading that ttl is in milliseconds, but it seems to be taking seconds as a value. Is that right? I'm on 3.4.0

**Comment by douglas-begg** [comment]
Yes before version 5 it was seconds. After it is milliseconds.

You can see the change documented in the change log: https://github.com/node-cache-manager/node-cache-manager/blob/master/CHANGELOG.md for the 5.0.0 version it states:
>  - Change ttl param unit to milliseconds
