### ISSUE TITLE
mget/mset does not exist when using multiCaching

### ISSUE THREAD

**Issue by deyhle** [node-cache-manager/node-cache-manager#361]
This worked in < v5, but now `mget` and `mset` are undefined on a multiCaching instance. `store.mget` and `store.mset` (taken from [the example for `mget` in the readme](https://github.com/node-cache-manager/node-cache-manager#example-settinggetting-several-keys-with-mset-and-mget)) is also undefined because `store` is undefined on a multiCaching instance.

Is it still possible to use `mget` and `mset` with multiCaching instances?

The test mentions the methods, but does not test for them: https://github.com/node-cache-manager/node-cache-manager/blob/a1eebf72bd60188e37f32dfb0c1e03ac23045c00/test/multi-caching.test.ts#L41

**Comment by botika** [comment]
Not at this time but it can be implemented.

**Comment by botika** [comment]
Fixes in `5.2.0`. Thanks!
