### ISSUE TITLE
Concurrent calls to `.wrap()` don't use the cached value

### ISSUE THREAD

**Issue by rdsfj** [node-cache-manager/node-cache-manager#395]
Heyo,

starting in version 5, concurrent calls to `.wrap(key, action)` each call the `action` to compute the value that should be cached. The behaviour only appears if the cache is empty for the given key.
Is this expected behaviour in version 5 or can we do something about it?

I created a small repo with a two tests as reproduction.
Run `npm ci && npm test` to see the results. I used node v18.12.1.
https://github.com/rdsfj/chache-manager-repro

Thanks!

**Comment by botika** [comment]
Yes, some like that
```
await Promise.all(wrap, wrap)
```
And this is so funny in single thread, but in real life in multiple thread. If you figure out a way to fix this by working with more than 1 thread, I'd appreciate it if you'd upload the PR.
