### ISSUE TITLE
TypeError: store.get is not a function with Cache Manager 5.2.0 in NestJS

### ISSUE THREAD

**Issue by KrishanAgg** [node-cache-manager/node-cache-manager#409]
I am using Cache Manager version 5.2.0 in my NestJS application to cache some data retrieved from my database. However, when I try to retrieve the cached data using this.cacheManager.get('degrees') in my getAll() method, I receive the following error:
`TypeError: store.get is not a function`

I do not want to downgrade the version of Cache Manager I am using. Can anyone help me resolve this issue?

Here is a snippet of my getAll() method for reference:
```async getAll(): Promise<DegreeDto[]> {
  const cachedDegrees: Degree[] = await this.cacheManager.get('degrees');
  if (cachedDegrees) {
    console.log({ cachedDegrees });
    return this.mapper.mapArrayAsync(cachedDegrees, Degree, DegreeDto);
  }
  const degrees = await this.degreeRepository.find({
    order: {
      sequence: 'ASC',
    },
  });
  await this.cacheManager.set('degrees', degrees);
  return this.mapper.mapArrayAsync(degrees, Degree, DegreeDto);
}```
I tried replacing Cache with Store but same error here are my imports :
``` @Inject(CACHE_MANAGER)
    private cacheManager: Cache,```

**Comment by gquittet** [comment]
Hello @KrishanAgg are you using Redis?

**Comment by botika** [comment]
Sorry, but is related to nestjs. Thanks!

**Comment by bertyhell** [comment]
@botika I have a similar issue, can you provide some info on how you solved your issue with nestjs?

**Comment by metaskills** [comment]
I just ran into this issue with `cache-manager-fs-hash` using the cache managers `wrap` function.

**Comment by metaskills** [comment]
Ah, my fix was here https://github.com/node-cache-manager/node-cache-manager/issues/258#issuecomment-1652212884
