### ISSUE TITLE
multi_caching checking all caches in series, even if value is found in first cache

### ISSUE THREAD

**Issue by 3choBoomer** [node-cache-manager/node-cache-manager#41]
This seems like a pretty large performance hit, especially since it doesn't appear to be needed.

The code in question:
https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/multi_caching.js#L80

It seems like relying on isCacheableValue to determine if we should return the result immediately doesn't make too much sense. Do we really care if the value is cacheable at this point? We just found it in the cache and we should defer to the set function to decide if it should be cached or not.

I've been doing some profiling and this popped out. I may raise a pull request if my testing proves this to be a net gain.

**Comment by BryanDonovan** [comment]
Yeah, it's possible that that could be removed.  I can't remember why it's there honestly.  I doubt it's a big performance hit, especially if redis, etc. is taking a few milliseconds anyway.

**Comment by 3choBoomer** [comment]
I probably have a special use case that can be found here: 
https://github.com/dial-once/node-cache-manager-redis/issues/19

In my testing it effectively doubles the time it takes to get something from the cache, but that's because my multi cache is a cluster of redis machines behind a load balancer, and then the master of that cluster. This way I can write to the master, but read from any of the machines behind the load balancer.

(BTW, thanks for the quick response!)

**Comment by BryanDonovan** [comment]
Are you using the `neverCache` function (or equivalent) as your `isCacheableValue` function?

**Comment by 3choBoomer** [comment]
Yes, I am for the first cache in my multiCache. 

My intention is to check the load balancer first, break out of the search for the item, and then write it only to the master node.

I raised a pull request:
https://github.com/BryanDonovan/node-cache-manager/pull/42

**Comment by BryanDonovan** [comment]
Oh, the reason we use `isCacheableValue` in that spot is because if, for example, `null` is a cacheable value, and it's found in the first cache, we don't want to keep checking the other caches.  Instead, we want to return `null` right away.

**Comment by 3choBoomer** [comment]
That use case makes sense, but if one is caching larger values (like a serialized object) in the cache, wouldn't you want to return that as soon as it's found instead of looking for it again?

The check for null would be really fast, even if it has to look for it in a different cache.

I can see the value of what you're saying, though. Maybe we need another function to determine if the null is a valid value?

**Comment by BryanDonovan** [comment]
Hmm.. I'm probably not following completely.   The intention is that if a value is found, like a large serialized object, it should return it immediately and not look for it in other caches.  In that case your `isCacheableValue` function could be `function(value) { return !!value; }` or something like that.

**Comment by BryanDonovan** [comment]
OK, I think I see what you're saying now.  Not sure how to get around that, other than perhaps having two functions, `isCacheableValue` and `isReturnableValue`.  By default `isReturnableValue` could just be set to `isCacheableValue`.  Not sure if that solves anything though.

**Comment by 3choBoomer** [comment]
Yes, that is what I was suggesting. I'll take a stab at it and update my PR.

**Comment by 3choBoomer** [comment]
@BryanDonovan finally got around to getting those unit tests in.

**Comment by BryanDonovan** [comment]
Sorry @3choBoomer -- I didn't see your comment here. Can you merge the latest from upstream/master and add the same isReturnableValue logic to lib/caching.js as well please? Then I think it's good to go.

**Comment by botika** [comment]
Fixes by #203
