### ISSUE TITLE
"Semaphore-driven" cache

### ISSUE THREAD

**Issue by dberardo-com** [node-cache-manager/node-cache-manager#496]
in my use case, different client can fire similar queries concurrently to the same backend. those queries would be like:

`GET_WEATHER_FORECAST("next hour")`

lets assume that the function above can be cached with a TTL of, say 5 minutes.

By using the simple implementation of cacheManager shown in the readme, i woudl end up having a system that every 5 minutes would run some number of parallel queries at the same time, before one of them gets cached. But this queries are all the same ... so can this be avoided, so that only 1 query is run each time TTL elapses?

the idea would be to use a sort of semaphore, like:

```
if(!cache.get("weather_key")){
if(!cache.get("weather_key_semaphore")){
   cache.set("weather_key_semaphore" ,"query is running..")
   cache.set("weather_key" ,await run_query())
 cache.clear("weather_key_semaphore")
} else {
... subscribe to cachekey and unlock when semaphore has unlocked ... or when timeout expires
return cache.get("weather_key")
}
}
```

is there already an off-the-shelf solution for this ? 
and if not: is it possible to subscribe to cache key changes ?

**Comment by botika** [comment]
just use `await`

**Comment by dberardo-com** [comment]
maybe my request wasnt clear enough. there is nothing to await on, i need to subscribe to cache events.

is it possible to subscribe to cache events only with redis or also with inMem cache ?

basically i am trying to find a solution which is indipendent from the specific cache engine implementation.

> just use await

do you mean that it is possible to run `await  cache.get("weather_key")` to "wait until that key gets a value"?

@botika

**Comment by botika** [comment]
@dberardo-com 

It doesn't make sense to put a trigger to the ttl because it's not a timeout, put a setTimeout if you need something to be fired. But as its name indicates, a TTL is not an event that can't be passed a callback and triggered when something happens. A TTL is **Time-to-live** , that is to say, that its only responsibility is to say the time that it **will be alive**.

The await was because it happens that for these issues that have nothing to do with open source **they usually pay me money**. So that you get used to the idea, it is as if I sent you an email saying that you give me 1000 dollars because I am me.

Thanks! :smile:

**Comment by dberardo-com** [comment]
> The await was because it happens that for these issues that have nothing to do with open source they usually pay me money.

good for you, i was not aware of this policy so i have decided to open up an issue all the same. But i still believe this is a feature which could be generally useful and i have always wondered why cache systems dont implement it by default


> It doesn't make sense to put a trigger to the ttl because it's not a timeout, put a setTimeout if you need something to be fired. But as its name indicates, a TTL is not an event that can't be passed a callback and triggered when something happens. A TTL is Time-to-live , that is to say, that its only responsibility is to say the time that it will be alive.

quoting myself:

> ... subscribe to cachekey and unlock when semaphore has unlocked ... or when timeout expires

i am not suggesting to subscribe to the key expiration but instead to the new key being populated / updated.

basically the flow would be the following.

- cache consumers A and B want to acccess key X
- consumer A sees that X is not defined and "locks it" (cache.set("X","LOADING")
- consumer B sees that X is locked and waits until its value has been updated, or till a timeout has expired (to avoid dead-locks)
- consumer A has now produced a new value for the cache and updates it cache.put("X","NEW_VALUE")
- consumer B receives a notification and reads the new value

hope this makes sense

**Comment by dberardo-com** [comment]
ok i have implemented an override for cacheManager and used it in a nestJS app with a redis store. I can share the solution if anyone is interested.

Btw, is there a way to fallback to in-memory cache in case redis is disconnected ?
