### ISSUE TITLE
creation of cache-manager-fs-stream

### ISSUE THREAD

**Issue by phoenix741** [node-cache-manager/node-cache-manager#497]
Hi,

To replace cache-manager-fs-binary that not working with cache-manager (because not using promise correctly) i have rewriting it in typescript : cache-manager-fs-stream.

The source code is here : https://github.com/phoenix741/node-cache-manager-fs-binary

If you want to reference it in the README., you can.

Thanks

**Comment by botika** [comment]
Thank you very much, feel free to do the PR. Add codecov or some similar tool please. In this repository have the code of how to do it.

**Comment by jaredwray** [comment]
Will be moving this to Keyv and they will be building a file based storage adapter. Feel free to do a pull request there. https://github.com/jaredwray/keyv
