### ISSUE TITLE
Versioning semantics and breaking changes

### ISSUE THREAD

**Issue by nutgaard** [node-cache-manager/node-cache-manager#504]
Seems like [this commit](https://github.com/node-cache-manager/node-cache-manager/commit/87efeffb63363183d6646ec24c3e243e4bbb93ce) introduced a breaking change into this library; whereas `keyCount()` was renamed into `size`. But released with a patch-version.

I could not find any information in this repository about semantic versioning, or if this repository follows another versioning scheme. My assumption (and I believe many share this) was therefore that breaking changes were accompanied by a bump i major-versions.

By design, or mishap, I just wanted to open a issue to get some clarity into what I should expect.

**Comment by botika** [comment]
My bad. The versioning follows the normal standards, I'm sorry if it caused you any problems.
