### ISSUE TITLE
Documentation for default memory store

### ISSUE THREAD

**Issue by jpham005** [node-cache-manager/node-cache-manager#522]
Since default memory store's `set` uses `lodash.clonedeep`, [some kind of values](https://lodash.com/docs/4.17.15#clone) cannot be cached.

Example
```ts
import { ObjectId } from 'bson'; // v5.3.0
import { caching } from 'cache-manager'; // v5.2.3
import cloneDeep from 'lodash.clonedeep'; // v4.3.0

const testId = new ObjectId('645763ee34dbf97f5ac101e9'); // has OwnPropertyDescriptors
const map = new Map();
map.set('testKey', testId);

const mem = await caching('memory', { max: 100, ttl: 100000 });

await mem.set('key', map);
// objectId throws exception because it's property descriptors are not exist anymore.
console.log(await mem.get('key'));
// this also fails. https://lodash.com/docs/4.17.15#clone
console.log(cloneDeep(map));
```

Above example, ObjectId has custom `inspect` function which returns it's private property,
but `lodash.clonedeep` doesn't make copy of it.

So the question is, is this an intended behavior or not?
If the answer is yes, it could be nice to have an additional comment about this.

**Comment by botika** [comment]
The doc is that https://lodash.com/docs/4.17.15#cloneDeep and use only in DTO like structures

**Comment by jpham005** [comment]
Thanks for the fast reply @botika !
But to be sure, I wanna know that I understood your word correctly.
**Do you mean that I should call `set` function with only DTO like structures?**

I read about both `clone` and `cloneDeep` docs, and also `node-cache-manager`'s default memory store code.
And as I understand,
1. Default memory store clone values by default before set.
```ts
const shouldCloneBeforeSet = args?.shouldCloneBeforeSet !== false; // clone by default // memory.ts :37
```
2. Default `isCacheable` function checks only undefined value.
```ts
const isCacheable = args?.isCacheable ?? ((val) => val !== undefined); // memory.ts :38
```
3. And the memory store calls `clone` value before call `lruCache.set`
```ts
async set(key, value, opt) {
  if (!isCacheable(value))
    throw new Error(`no cacheable value ${JSON.stringify(value)}`);
  if (shouldCloneBeforeSet) value = clone(value);

  const ttl = opt !== undefined ? opt : lruOpts.ttl;

  lruCache.set(key, value, { ttl });
},
```
4. `clone` function checks that the `typeof parameter` is object, and the value exists.
```ts
function clone<T>(object: T): T {
  if (typeof object === 'object' && object !== null) {
    return cloneDeep(object);
  }
  return object;
}
```
5. And in my example code, the map I created satisfies above conditions, so `cloneDeep` is going to be called with my map!
6. It'll cause errors. Now then, should I provide `isCacheable` function or just do not cache non-DTO like structures?
And I thought that it will be good to have answer about this in README.
