### ISSUE TITLE
Unable to access keys each time incase of Redis Cluster

### ISSUE THREAD

**Issue by gerardvc** [node-cache-manager/node-cache-manager#573]
Hi,

I have integrated the cache manager in my NestJs app and am able to push data into my Redis Cluster.
However whenever I try and retrieve all the keys I am not able to get the data at all times.
Sometimes I get the data and at other times I get an empty array.
What could be the reason for this?

```
      const keys = await this.cacheManager.store.keys('notification*');
      console.log(keys);
```

Response:
First Time: []
Second Time: ['notification', 'notification2']
Third Time: []

**Comment by gerardvc** [comment]
Yes was using ioredis.I added the ENV variable and got the below logs
```
  ioredis:cluster cluster slots result [1]: slots 0~5460 served by [
  '127.0.0.1:7001',
  '127.0.0.1:7005',
  '127.0.0.1:7004',
  '127.0.0.1:7006'
  ] +0ms
    ioredis:cluster cluster slots result [1]: slots 0~5460 served by [
  '127.0.0.1:7001',
  '127.0.0.1:7005',
  '127.0.0.1:7004',
  '127.0.0.1:7006'
] +0ms
  ioredis:redis status[127.0.0.1:7003 (ioredis-cluster(refresher))]: ready -> close +16ms
  ioredis:connection skip reconnecting since the connection is manually closed. +17ms
  ioredis:redis status[127.0.0.1:7003 (ioredis-cluster(refresher))]: close -> end +1ms
  ioredis:redis status[127.0.0.1:7001]: wait -> connecting +3s
  ioredis:redis queue command[127.0.0.1:7001]: 0 -> keys([ 'notification*' ]) +1ms
  ioredis:redis status[127.0.0.1:7001]: connecting -> connect +1ms
  ioredis:redis write command[127.0.0.1:7001]: 0 -> info([]) +1ms
  ioredis:redis status[127.0.0.1:7001]: connect -> ready +1ms
  ioredis:connection send 1 commands in offline queue +3s
  ioredis:redis write command[127.0.0.1:7001]: 0 -> keys([ 'notification*' ]) +0ms
[]
```

**Comment by BryanDonovan** [comment]
Oh... Redis Cluster doesn't let you get all the keys in the cluster that way.  You can do `GETKEYSINSLOT` for each slot (https://redis.io/commands/cluster-getkeysinslot/) manually.  There might be a way using ioredis to get each slot and run `keys` for each.  

However, make sure you really want to do this.  Fetching all the keys is a slow operation.

**Comment by gerardvc** [comment]
Thanks.This link was also helpful incase anyone needs an indepth explanation while working with Redis Cluster.
https://stackoverflow.com/questions/73556888/redis-cli-keys-not-showing-all-keys
