### ISSUE TITLE
need wrapSync Function?

### ISSUE THREAD

**Issue by radiorz** [node-cache-manager/node-cache-manager#576]
when some function is sync function ,if wrap it will be a async function
how to make it sync

**Comment by botika** [comment]
```typescript
const yourFunctionAsync = async () => yourFunction();
```
Say that?

**Comment by radiorz** [comment]
```javascript
const wrapFunctionSync = ()=> wrapSync(myFunctionSync())
```
the cachemanager wrap will return promise,need await.

**Comment by BryanDonovan** [comment]
What situation do you have where you need to use a synchronous cache function?

**Comment by jaredwray** [comment]
@radiorz - I know you are busy. Let  us know the use case but to be honest I think we would avoid trying to force a Sync on wrap at this time.

**Comment by radiorz** [comment]
it is just a case that original function is sync function, and i use it a lot without add await). if i use cacheManager to wrap it, i should add many await when using the wrapfunction.
if there is a wrapSync function that we can avoid await-hell.

**Comment by BryanDonovan** [comment]
Is this an in-memory cache?

The original point of cache-manager was to make dealing with callback-based caching easier.  With synchronous code (and even with async/await), it’s pretty easy to write simple if-else logic to handle caching.

**Comment by jaredwray** [comment]
Agree with @BryanDonovan as it makes more sense to do an if/else. Happy to look at a pull request but closing for now.
