### ISSUE TITLE
Cache error fallback (bis)

### ISSUE THREAD

**Issue by MathieuGuillet** [node-cache-manager/node-cache-manager#588]
Hello 👋 !
This subject has already been talked about in [this issue](https://github.com/node-cache-manager/node-cache-manager/issues/51) :
> If the call to the cache store fails. Should it fall back to the wrapped function?

We are facing the same issue/requirement using the `cache.wrap(...)` function : if a call to a multi-cache store fails (in-memory + redis), let's say because Redis is unreachable, then we would expect the cache-manager to call the wrapped function instead of raising an error.

Shouldn't the cache act as a performance optional path to get data, but not interfere to get this data if it is facing errors ?

There used to be a `ignoreCacheErrors` flag to activate this behavior, but it has been removed in the 5.0.0 version.
Is it possible to reintroduce it ?

Thanks 🙌

**Comment by jaredwray** [comment]
Hi @MathieuGuillet - we are working on this issue with Keyv version 5 as it should not cause a failure and will use the same code to fix this module. This might take about 60 days to resolve. Just FYI

**Comment by slukes** [comment]
Hello @jaredwray do you have an issue to follow to know when it is good?
