### ISSUE TITLE
TypeScript: increase target to ES2017+

### ISSUE THREAD

**Issue by icholy** [node-cache-manager/node-cache-manager#597]
**Is your feature request related to a problem? Please describe.**

The generated code has the async/await code down-compiled to generators. This makes debugging it annoying.

**Describe the solution you'd like**

Change the `target` in `tsconfig.json` to `ES2017` or higher (NodeJS 8+). For context, NestJS is using `ES2021` (NodeJS 16+).

**Comment by jaredwray** [comment]
Hi @icholy we will be looking to do this breaking change in the next 30-60 days with some additional features

**Comment by jaredwray** [comment]
@icholy - this has now been merged and will be released in a week or so.
