### ISSUE TITLE
Adding  refreshThreshold Parameter to the wrap Function

### ISSUE THREAD

**Issue by eternasuno** [node-cache-manager/node-cache-manager#606]
The cache's  TTL can vary significantly, for instance, between 5 minutes and 1 day. It's challenging to determine a single, unified refreshThreshold setting for all use cases. Therefore, adding a separate refreshThreshold parameter to the wrap function could be a valuable enhancement.

**Comment by jaredwray** [comment]
@eternasuno - can you give a couple examples of this use case?
