### ISSUE TITLE
5.3.0 missing `dist/` folder on npmjs.org

### ISSUE THREAD

**Issue by danieljcerno** [node-cache-manager/node-cache-manager#611]
Hi team,

The `5.3.0` release of cache-manager appears to be missing the `dist/` folder when installed from `npmjs.org`.

[https://www.npmjs.com/package/cache-manager/v/5.2.4?activeTab=code](5.2.4)
[https://www.npmjs.com/package/cache-manager/v/5.3.0?activeTab=code](5.3.0)

Am I missing something?

**Comment by Bojianye** [comment]
Same, the cache-manager folder does not contain any source code.

**Comment by kimtiago** [comment]
up!

**Comment by waynemamahit** [comment]
Up!

**Comment by mmendivilg** [comment]
Up!

**Comment by dhianica** [comment]
up

**Comment by mmendivilg** [comment]
My production app is not deploying because of this error:

[Nest] 14136  - 11/16/2023, 7:51:25 PM   ERROR [PackageLoader] The "cache-manager" package is missing. Please, make sure to install this library ($ npm install cache-manager) to take advantage of CacheModule.

I was wondering if anyone can tell me what to do to fix this temporarily?

**Comment by kimtiago** [comment]
> My production app is not deploying because of this error:
> 
> [Nest] 14136 - 11/16/2023, 7:51:25 PM ERROR [PackageLoader] The "cache-manager" package is missing. Please, make sure to install this library ($ npm install cache-manager) to take advantage of CacheModule.
> 
> I was wondering if anyone can tell me what to do to fix this temporarily?

add `"cache-manager": "5.2.4" ` as dependency of your package.json, this will force to use this version

**Comment by mmendivilg** [comment]
> > My production app is not deploying because of this error:
> > [Nest] 14136 - 11/16/2023, 7:51:25 PM ERROR [PackageLoader] The "cache-manager" package is missing. Please, make sure to install this library ($ npm install cache-manager) to take advantage of CacheModule.
> > I was wondering if anyone can tell me what to do to fix this temporarily?
> 
> add `"cache-manager": "5.2.4" ` as dependency of your package.json, this will force to use this version

Thank you for the quick reply
despite having in my package.json

    "cache-manager": "^5.2.1",
    
    I keep getting this errorr:
    
    Nov 17 02:45:12 ip-172-31-38-180 web: #033[96msrc/app/tenant/roles/services/roles-cache.service.ts#033[0m:#033[93m1#033[0m:#033[93m23#033[0m - #033[91merror#033[0m#033[90m TS2307: #033[0mCannot find module 'cache-manager' or its corresponding type declarations.
Nov 17 02:45:12 ip-172-31-38-180 web: #033[7m1#033[0m import { Cache } from 'cache-manager';

**Comment by mtripathy-palo** [comment]
@mmendivilg - You would have to use the tilde with the version
"cache-manager": "~5.2.1",

This will ensure the version stays as 5.2.x (only the patch number gets bumped)

**Comment by mmendivilg** [comment]
> @mmendivilg - You would have to use the tilde(~) and not ^ with the version "cache-manager": "~5.2.1",
> 
> This will ensure the version stays as 5.2.x (only gets bumped to patch versions when available). In this case 5.3.0 is the failing version.

Saved my life. Thank you

**Comment by yurikgs** [comment]
same problem here :)

**Comment by yeli19950109** [comment]
same problem

**Comment by salmanx** [comment]
Same problem! No src or dist folder inside cache manager codebase in node modules.

**Comment by md-redwan-hossain** [comment]
same problem

**Comment by anhhaduy1** [comment]
+1

**Comment by QuentinLemCode** [comment]
+1

**Comment by QuentinLemCode** [comment]
I suggest an automated workflow for avoid this in the future : https://github.com/node-cache-manager/node-cache-manager/pull/612

**Comment by aretit2533** [comment]
+1

**Comment by leifermendez** [comment]
up

**Comment by FabianMeul** [comment]
+1

**Comment by jandersonTIC** [comment]
up!

**Comment by nikhildoifode** [comment]
+1

**Comment by jason2han** [comment]
up!

**Comment by joepegler** [comment]
+1

**Comment by jaredwray** [comment]
Hi All. Sorry for the failure and I am working on a publish now. It should be out in the next hour.

**Comment by jaredwray** [comment]
This has been released with a dist folder `5.3.1`. Again, this was my fault and I will make it so it doesnt happen again.

**Comment by QuentinLemCode** [comment]
@jaredwray can you look at this PR please : https://github.com/node-cache-manager/node-cache-manager/pull/612
