### ISSUE TITLE
Q: question regarding using keys()

### ISSUE THREAD

**Issue by jxjgao** [node-cache-manager/node-cache-manager#629]
Hello,

I noticed that in a **single tier cache**, I can use this.cache.caches[0].keys() to get an array of all the keys in the in memory store. However, when trying to access this.cache.caches[0].keys() when this.cache is a multi-tier cache, and this.cache.caches[0] is the in memory store in the multi-tier cache, this.cache.caches[0].keys() returns me an empty array. I am aware that it is not advised to fetch all keys at once, but just wondering if there was a reason why fetching keys() from the single tier cache works, but for the multi-tier cache it doesn't.

I am using cache-manager 3.6.1 and was wondering if I would run into the same errors on the newer version of 5.3.2. 

Thank you in advance for any replies.

**Comment by jaredwray** [comment]
@jxjgao - hello. This is not really supported in `cache-manager` and you might want to look at something like `keyv` to do this a bit easier.
