### ISSUE TITLE
Under constant load, backend refresh doesn't provide efficient mechanism to save enought backend request

### ISSUE THREAD

**Issue by lchenay** [node-cache-manager/node-cache-manager#631]
**Is your feature request related to a problem? Please describe.**

If the system is under constant load, let say 100#/s on 10 different instance with 1s backend request when refreshThreshold reach 10 requests will generate a backend request as the 10 instances will see an opportunity of background refresh (of course promise-coalesce does a great job by sending only 10 instead of 100).

On some big infrastructure, with 200-300 instances, those littles over head could have significant impact.

**Describe the solution you'd like**

Not real solution to propose, let's open discussion.

Any kind of locking mechanism between instance may be complex / error prone.

I'm thinking about some kind of opportunistic background refresh, using random, proportionaly to how much ttl remain:
`if (remainingTtl !== -1 && remainingTtl < args.refreshThreshold) {` => `if (remainingTtl !== -1 && Math.random() < 1 - remainTTL / args.refreshThreshold) {`

**Comment by jaredwray** [comment]
@lchenay - that is something that could be possible but I would think that we remove the background refresh at scale as that causes other issues or go to a Kafka like infrastructure to update the caching stores directly which is what most larger scale enterprises do. Putting this into the library could cause multiple issues when you have 100s of nodes trying to do a refresh.

**Comment by lchenay** [comment]
I would love to switch to a read model infrastructure. Sadly it's not easily possible and we have to deal with it in short term.

Totally agree on your feedback and the decision to not put it natively in the library.

We will find a solution on our side
