### ISSUE TITLE
Support hset hget

### ISSUE THREAD

**Issue by namhihi237** [node-cache-manager/node-cache-manager#633]
**Is your feature request related to a problem? Please describe.**
I have noticed that the current implementation of node-cache-manager lacks support for the hset and hget operations. These operations are crucial for scenarios where a hash-like data structure is needed, and their absence restricts certain use cases

**Describe the solution you'd like**
I would like to request the addition of hset and hget support in node-cache-manager. This would enhance the functionality of the library by allowing users to efficiently manage and retrieve data using hash keys.

```js
const userId = 1;

const userDetails = {
  name: 'John Doe',
  email: 'john@example.com',
  // other user details
};

memoryCache.store.hset(userId, 'userDetails', userDetails);

const cachedUserDetails = cache.hget(userId, 'userDetails');

```
Thank you for considering this feature request!

**Comment by jaredwray** [comment]
Thanks @namhihi237 and at this time we are not going to be supporting this as our goal is to support multiple back ends which this could cause issues.
