### ISSUE TITLE
Optimizing Multicaching Efficiency: Dynamic Data Migration Between Cache Levels

### ISSUE THREAD

**Issue by EliezerMafra** [node-cache-manager/node-cache-manager#639]
**Is your feature request related to a problem? Please describe.**
Imagine a scenario where we implement multicaching with two cache managers, operating as distinct levels:

- Memory Cache
- Redis Cache

While these caches have different TTLs (Time To Live), an issue arises when the memory cache expires. At that point, multicaching resorts solely to fetching data from Redis until it also expires. This contradicts the intended purpose of multicaching, which is to minimize Redis calls by efficiently storing data in memory.

**Describe the solution you'd like**
To address this, we propose an enhancement where, in situations where data is not found in the first cache level but is available in the second, the system should dynamically copy the data from the second level to the first. Subsequent calls would then benefit from improved performance, as data retrieval occurs primarily from the faster memory cache.

Consider the following workflow:

- Upon the first call, if data isn't found in the primary cache level, the system queries the secondary cache.
- Upon finding the data in the secondary cache, it's copied to the primary cache.
- Subsequent calls retrieve data directly from the primary cache, thus enhancing performance by reducing reliance on the secondary cache.

**Comment by jaredwray** [comment]
@EliezerMafra thanks for bringing this to our attention. Would love to see a test example of this and then we can get a fix going.

**Comment by eliezermafra-ecotrak** [comment]
@jaredwray I can raise a PR for that if you want

**Comment by erkstruwe** [comment]
This already works, but only when using `wrap`. See #253.
