### ISSUE TITLE
Add the shouldCloneBeforeSet option to the documentation

### ISSUE THREAD

**Issue by adelbke** [node-cache-manager/node-cache-manager#640]
**Is your feature request related to a problem? Please describe.**
I am trying to cache Query results in my project to speed up subsequent database lookups
I tried to cache Mongoose documents. Deep cloning them results in stack exhaustion as they are not designed to be cloned.
Since I only keep the values in the cache for a short term and I am aware of the risks of mutating them I set the `shouldCloneBeforeSet` option to `true`

unfortunately, I couldn't find the documentation related to the option. I had to look into the issues section like this one #135 and also this one #522 and also stumbled upon it in the code of the library.

**Describe the solution you'd like**
- Add the option `shouldCloneBeforeSet` to the documentation

**Comment by jaredwray** [comment]
Just added this here: https://github.com/node-cache-manager/node-cache-manager/pull/644
