### ISSUE TITLE
cache prefix

### ISSUE THREAD

**Issue by tarikhagustia** [node-cache-manager/node-cache-manager#642]
**Is your feature request related to a problem? Please describe.**
Currently im using redis server with multiple project, when i need to clean all cache related project A for eg, it its quite hard because we can't identify which cache belong to.

**Describe the solution you'd like**
it will be good if we have the cache prefix that is configurable via module for example we can set to nestjs:* so when we need to delete the cache, we can delete it by prefix and the other cache that is not related to a specific project is not deleted

**Comment by jaredwray** [comment]
@tarikhagustia I do believe that as we integrate Keyv (https://keyv.org) into this project this feature will happen. Our goal is to implement it over the next 3-4 months. FYI
