### ISSUE TITLE
multi_caching causes invalid TTL entries

### ISSUE THREAD

**Issue by dcolens** [node-cache-manager/node-cache-manager#67]
It looks like multi-caching can cause invalid TTL (https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/multi_caching.js#L160). For example let's assume the highest priority is memory followed by a shared storage such as a DB:
   - an entry is cached in DB
   - the service is stopped then restarted 
   - the next time that entry is queried it will be populated from the DB cache to the memory cache with a default TTL which is > than the real TTL in the DB.

A more realistic example is where multiple services share the cache, in that scenario:
   - SERVICEA sets `ENTRY1`
   - SERVICEB gets `ENTRY1`, it is in DB cache but not in memory so it sets with the default TTL in memory cache resulting in both services to have out of sync cache entries.

A solution is to pass the TTL from a lower cache level to a higher cache level when populating it, this would require that `wrap` or `get` return the TTL of the entry as an extra arg.

**Comment by BryanDonovan** [comment]
Thanks @dcolens.  Do you want to try implementing this?  Otherwise I can try when I have time, but it might be a week or so.

**Comment by astanciu** [comment]
Any updates on this? Seems like a pretty big problem for multi-caching...

**Comment by BryanDonovan** [comment]
Sorry, I didn't hear back from you.. I was wondering if you wanted to try implementing the solution.  I'm pretty busy these days but will get to it eventually.

**Comment by dcolens** [comment]
I don't have time right now for implementing, I found the issue while experimenting with multi-caching, I like the concept a lot!

**Comment by BryanDonovan** [comment]
I'm not sure how feasible this is.  The problem I see is that you don't necessarily know the TTL of the entry from the lower cache, so you can't be sure to pass it up to the higher cache. 

I might be missing something, but it seems like the worst case scenario is a rare cache miss.. correct me if I'm wrong though.

**Comment by dcolens** [comment]
In the scenario where multiple servers are used for load balancing it will cause cache inconsistency. For example: serverA caches entryA, serverB gets a query for entryA it finds it in the lower level cache and caches it in the mem cache, now entryA will still be present in serverB while it already expired in serverA.

 In my use case, this made the functionality unusable. So yes, in my opinion the lower level caches should return the remaining TTL when queried in a multi-cache scenario.

**Comment by BryanDonovan** [comment]
Hmm.  I see the benefits of your proposed solution, but I'm not seeing an easy solution that fits all scenarios.

The original intent of the multi-cache, if used with a memory cache, is to have a very short TTL for the memory cache compared to the lower cache.  E.g, you would perhaps only want to cache data in memory with a TTL of 5 minutes with a redis backend that has a TTL of 24 hours.

I don't think most people would have the higher level cache have a similar TTL as the lower level cache, and therefore wouldn't want the higher cache to receive the remaining TTL from the lower cache. 

Providing options that allow this to be configurable seems like it would be pretty confusing.  I'm open to ideas though.

**Comment by vmattila** [comment]
I am bumbing up this issue/question as struggling also with some inconsistency in multi_caching policies.

In my opinion, TTL values should always be considered as maximum time an entry is kept in cache. Store implementations can always purge the cache entry before TTL but "never" after. Thus, higher level caches should always have lower TTL than lower level level caches. For me, it makes no sense to have TTL of 10 sec in memory but 5 sec in redis.

TTLs per item are indeed tricky. Again, in my personal opinion, if default TTL for a store is lower than item TTL, the store TTL should be used. For example, if I have cache layers memory (10 sec TTL) and redis (60 sec TTL), and then set item with TTL 30 sec; memory layer should have it for 10 sec and redis for 30 sec.

I did also notice that https://github.com/theogravity/node-cache-manager-memory-store does not implement TTL at all, so all cache items would be kept in cache forever, won't they? This might be worth another issue & PR though. ;)

**Comment by websocket98765** [comment]
> I did also notice that https://github.com/theogravity/node-cache-manager-memory-store does not implement TTL at all, so all cache items would be kept in cache forever, won't they? This might be worth another issue & PR though. ;)

I haven't looked into the implementation, but wanted to note I tested the built-in memory store tonight using a TTL set on the memory store, and it worked successfully--it returned cached items within the TTL timeframe and returned undefined after the expected TTL elapsed.

**Comment by botika** [comment]
Fixes by #203
